spring:
  application:
    name: inventory-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventorydb}
    username: ${SPRING_DATASOURCE_USERNAME:inventory}
    password: ${SPRING_DATASOURCE_PASSWORD:inventory}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 250ms
          multiplier: 2.0
          max-interval: 2s
        default-requeue-rejected: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        request:
          autotime:
            percentiles-histogram: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0

server:
  port: ${SERVER_PORT:8082}

app:
  reservation-ttl: PT10M
  demo:
    category1-ticket-category-id: 11111111-1111-1111-1111-111111111111
    category2-ticket-category-id: 22222222-2222-2222-2222-222222222222
