spring:
  application:
    name: ticket-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketdb}
    username: ${SPRING_DATASOURCE_USERNAME:ticket}
    password: ${SPRING_DATASOURCE_PASSWORD:ticket}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        request:
          autotime:
            percentiles-histogram: true

server:
  port: ${SERVER_PORT:8085}
